"""add swipe model

Revision ID: 8d5d79c8c271
Revises: 8c3d54649c67
Create Date: 2026-02-19 19:36:13.312228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d5d79c8c271'
down_revision: Union[str, Sequence[str], None] = '8c3d54649c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swipes',
    sa.Column('first_user_id', sa.Integer(), nullable=False),
    sa.Column('second_user_id', sa.Integer(), nullable=False),
    sa.Column('first_decision', sa.Boolean(), nullable=False),
    sa.Column('second_decision', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['first_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['second_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('first_user_id', 'second_user_id')
    )
    op.add_column('users', sa.Column('gender', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_table('swipes')
    # ### end Alembic commands ###
