"""changes to the images model

Revision ID: a9b19e951854
Revises: e4e4e6a81464
Create Date: 2026-02-17 19:21:33.896549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b19e951854'
down_revision: Union[str, Sequence[str], None] = 'e4e4e6a81464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('order', sa.Integer(), nullable=False))
    op.add_column('images', sa.Column('is_main', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'is_main')
    op.drop_column('images', 'order')
    # ### end Alembic commands ###
