"""Change swipe action type

Revision ID: b11dd5ad16e2
Revises: 8d5d79c8c271
Create Date: 2026-02-19 20:15:59.540074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b11dd5ad16e2'
down_revision: Union[str, Sequence[str], None] = '8d5d79c8c271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swipes', sa.Column('first_action', sa.Integer(), nullable=False))
    op.add_column('swipes', sa.Column('second_action', sa.Integer(), nullable=True))
    op.drop_column('swipes', 'first_decision')
    op.drop_column('swipes', 'second_decision')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swipes', sa.Column('second_decision', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('swipes', sa.Column('first_decision', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('swipes', 'second_action')
    op.drop_column('swipes', 'first_action')
    # ### end Alembic commands ###
