"""add table of user images

Revision ID: e4e4e6a81464
Revises: ac9a56e73064
Create Date: 2026-02-16 00:32:57.722593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'e4e4e6a81464'
down_revision: Union[str, Sequence[str], None] = 'ac9a56e73064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('image', sa.String(length=200), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.add_column('users', sa.Column(
        'is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(), nullable=False))
    op.alter_column('users', 'latitude',
                    existing_type=sa.NUMERIC(precision=10, scale=8),
                    nullable=True)
    op.alter_column('users', 'longitude',
                    existing_type=sa.NUMERIC(precision=11, scale=8),
                    nullable=True)
    op.alter_column('users', 'geo_location',
                    existing_type=geoalchemy2.types.Geometry(
                        geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
                    nullable=True)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'geo_location',
                    existing_type=geoalchemy2.types.Geometry(
                        geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
                    nullable=False)
    op.alter_column('users', 'longitude',
                    existing_type=sa.NUMERIC(precision=11, scale=8),
                    nullable=False)
    op.alter_column('users', 'latitude',
                    existing_type=sa.NUMERIC(precision=10, scale=8),
                    nullable=False)
    op.drop_column('users', 'role')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'password')
    op.create_table('spatial_ref_sys',
                    sa.Column('srid', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('auth_name', sa.VARCHAR(length=256),
                              autoincrement=False, nullable=True),
                    sa.Column('auth_srid', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('srtext', sa.VARCHAR(length=2048),
                              autoincrement=False, nullable=True),
                    sa.Column('proj4text', sa.VARCHAR(length=2048),
                              autoincrement=False, nullable=True),
                    sa.CheckConstraint('srid > 0 AND srid <= 998999',
                                       name=op.f('spatial_ref_sys_srid_check')),
                    sa.PrimaryKeyConstraint(
                        'srid', name=op.f('spatial_ref_sys_pkey'))
                    )
    op.drop_table('images')
    # ### end Alembic commands ###
