"""rename distance->max_distance

Revision ID: fc202da5d775
Revises: e7218794dfc8
Create Date: 2026-02-22 15:36:11.132241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc202da5d775'
down_revision: Union[str, Sequence[str], None] = 'e7218794dfc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('max_distance', sa.Float(), nullable=False))
    op.drop_column('preferences', 'distance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('preferences', 'max_distance')
    # ### end Alembic commands ###
